/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Medicine {
  'id' : bigint,
  'featured' : boolean,
  'manufacturer' : string,
  'dosage' : string,
  'name' : string,
  'uses' : string,
  'warnings' : string,
  'barcode' : string,
  'genericName' : string,
  'category' : string,
  'sideEffects' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMedicine' : ActorMethod<[Medicine], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteMedicine' : ActorMethod<[bigint], undefined>,
  'getAllMedicines' : ActorMethod<[], Array<Medicine>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFeaturedMedicines' : ActorMethod<[], Array<Medicine>>,
  'getMedicine' : ActorMethod<[bigint], Medicine>,
  'getMedicineByBarcode' : ActorMethod<[string], Medicine>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasAnyAdmin' : ActorMethod<[], boolean>,
  'initializeSamples' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchMedicines' : ActorMethod<[string], Array<Medicine>>,
  'setFeatured' : ActorMethod<[bigint, boolean], undefined>,
  'updateMedicine' : ActorMethod<[bigint, Medicine], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];