/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Medicine = IDL.Record({
  'id' : IDL.Nat,
  'featured' : IDL.Bool,
  'manufacturer' : IDL.Text,
  'dosage' : IDL.Text,
  'name' : IDL.Text,
  'uses' : IDL.Text,
  'warnings' : IDL.Text,
  'barcode' : IDL.Text,
  'genericName' : IDL.Text,
  'category' : IDL.Text,
  'sideEffects' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMedicine' : IDL.Func([Medicine], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteMedicine' : IDL.Func([IDL.Nat], [], []),
  'getAllMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFeaturedMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getMedicine' : IDL.Func([IDL.Nat], [Medicine], ['query']),
  'getMedicineByBarcode' : IDL.Func([IDL.Text], [Medicine], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasAnyAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'initializeSamples' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchMedicines' : IDL.Func([IDL.Text], [IDL.Vec(Medicine)], ['query']),
  'setFeatured' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateMedicine' : IDL.Func([IDL.Nat, Medicine], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Medicine = IDL.Record({
    'id' : IDL.Nat,
    'featured' : IDL.Bool,
    'manufacturer' : IDL.Text,
    'dosage' : IDL.Text,
    'name' : IDL.Text,
    'uses' : IDL.Text,
    'warnings' : IDL.Text,
    'barcode' : IDL.Text,
    'genericName' : IDL.Text,
    'category' : IDL.Text,
    'sideEffects' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMedicine' : IDL.Func([Medicine], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteMedicine' : IDL.Func([IDL.Nat], [], []),
    'getAllMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFeaturedMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getMedicine' : IDL.Func([IDL.Nat], [Medicine], ['query']),
    'getMedicineByBarcode' : IDL.Func([IDL.Text], [Medicine], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasAnyAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'initializeSamples' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchMedicines' : IDL.Func([IDL.Text], [IDL.Vec(Medicine)], ['query']),
    'setFeatured' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateMedicine' : IDL.Func([IDL.Nat, Medicine], [], []),
  });
};

export const init = ({ IDL }) => { return []; };